# Configure Netlify to serve particular headers for certain routes
  # enable CORS on one of our string files to enable testing
[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"