[[headers]]
  for = "/*"

  [headers.values]
    Referrer-Policy = "origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type = "nosniff"
    # Multi-key header rules are expressed with multi-line strings.
    Content-Security-Policy = '''
      default-src 'self';
      connect-src 'self' https://p.trellocdn.com https://app.clickup.com;
      script-src 'self' https://p.trellocdn.com;
      style-src 'self' https://p.trellocdn.com;
      frame-ancestors https://trello.com; 
    '''
