[[headers]]
  # Enable CORS for all paths under your domain
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = ["https://send2clickup.netlify.app"]
      Access-Control-Allow-Methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      Access-Control-Allow-Headers = ["Content-Type"]
